### ISSUE TITLE
Rubocop testing

### ISSUE THREAD

**Issue by mvoland** [the-hacking-team/happy-minute#15]
How should we integrate Rubocop in our workflow?

**Comment by StanislasBASQUIN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rédiger et mettre en page le ReadME](https://trello.com/c/Q3Zder1Y/22-r%C3%A9diger-et-mettre-en-page-le-readme)

**Comment by mvoland** [comment]
See on trello https://trello.com/c/ZNJORRl7/102-testing-rubocop
