### ISSUE TITLE
Creating ERD for MVP

### ISSUE THREAD

**Issue by Vivien-Ploix** [the-hacking-team/happy-minute#16]
Implementing the ERD needed for the MVP, with the tables : 
-Item
-Business
-Consumer
-Happy Price
-Happy Code
-Administrator 
(Owner is already coded)

**Comment by mvoland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Modèles et migrations pour Business, ITem, Customer, Happy Price, Happy Code, Administrator](https://trello.com/c/WsS7HKeL/54-mod%C3%A8les-et-migrations-pour-business-item-customer-happy-price-happy-code-administrator)
