### ISSUE TITLE
Front CSS / SCCS / Bootstrap choice

### ISSUE THREAD

**Issue by mvoland** [the-hacking-team/happy-minute#3]

**Comment by mathieu-superpose** [comment]
Found this one that should solve our issue:

[https://stackoverflow.com/questions/19192747/how-to-dynamically-change-themes-after-clicking-a-drop-down-menu-of-themes](url)

**Comment by mvoland** [comment]
This Issue was meant to be about using SCSS vs plain CSS and bootstrap 

Meeting Sept, 4 => A lot of bootstrap with plain CSS
