### ISSUE TITLE
Validate on Happy Price dates and price

### ISSUE THREAD

**Issue by mvoland** [the-hacking-team/happy-minute#90]
Missing validate on Happy Price, e.g. https://github.com/the-hacking-team/happy-minute/compare/validate-happy-price

**Comment by Laurent-Gi** [comment]
this make lot's of trubles !
Can't create now any happy minute (but it is strange, it's work in local for Vivien but not for me and not in heroku)

**Comment by mvoland** [comment]
Fixed in same branch, works for me here https://test-happy-minute.herokuapp.com
